fix: telemetry for Abort (#4738)
* fix: telemetry for Abort

- Add Abort as an exit code that's no longer classified as 255
- Add OSError to the catch blocks for `sam init` such that a non
  existent zip location does not cause the cli to crash.
  ```
  sam init --location /path/to/template.zip
  Error: An error occurred while generating this project : [Errno 2] No such file or directory: '/path/to/template.zip'
  ```

* fix: tests for windows

---------

Co-authored-by: hnnasit <84355507+hnnasit@users.noreply.github.com>